# Generated by Django 3.0.4 on 2020-05-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowModel',
            fields=[
                ('followId', models.AutoField(primary_key=True, serialize=False)),
                ('userId_A', models.PositiveSmallIntegerField()),
                ('userId_B', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
