# Generated by Django 3.0.4 on 2020-03-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userId', models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, default='', max_length=50)),
                ('lastName', models.CharField(blank=True, default='', max_length=50)),
                ('about', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
