# Generated by Django 3.0.4 on 2020-04-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userId',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
